### ISSUE TITLE
poke["time"] contains what?

### ISSUE THREAD

**Issue by cytec** [TBTerra/spawnTracker#1]
just wondering what timestamp it holds? 
`timeSpawn = (curTime+(wild['time_till_hidden_ms']))-900000``

seems to be current `current timestamp + time till hidden - 15 minutes` is that correct?

**Comment by TBTerra** [comment]
yes, thatis the assumes time of spawning (it works out when it will despawn and assumes that it spawns 15mins before that (although this has been shown to only be true 98% of the time[a few spawns have longer times])

**Comment by cytec** [comment]
so thats basically the guessed time the pokemon spawned at that location not the time it despawned?

**Comment by TBTerra** [comment]
(curTime+(wild['time_till_hidden_ms'])) is the time it despawns, so yes its a guess at when it spawned

**Comment by cytec** [comment]
Thanks for clearing that up :)
